;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█░░░█▀█░█▀▄░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░░░█░█░█▀▄░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀▀▀│
;; │░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░│
;; └────────────────────────────────────────────────────────────┘

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

 background = #cc1e1e2e
 foreground = #bac2de
 sep = #7f849c

 white = #b4befe
 black = #11111b
 red = #eba0ac
 pink = #f5c2e7
 purple = #cba6f7
 blue = #89b4fa
 cyan = #89dceb
 teal = #94e2d5
 green = #a6e3a1
 lime = #a6e3a1
 yellow = #f9e2af
 amber = #f38ba8
 orange = #fab387
 brown = #fab387
 indigo = #74c7ec
 gray = #585b70
 blue-gray = #7f849c

